apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
  namespace: project
spec:
  type: NodePort
  selector:
    app: log-output
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP