apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: shared-route
  namespace: project
spec:
  parentRefs:
    - name: shared-gateway
      sectionName: http

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /pingpong
      backendRefs:
        - name: ping-pong-svc
          port: 80

    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: log-output-svc
          port: 80